services:
  mysql:
    image: mysql:8
    container_name: mysql8-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3308:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
